#*********************************************************************************** 
#* Name        : chatclient.c
#* Author      : Sydney Cardy and Rafael Sanchez
#* Date        : 7 May 2021
#* Pledge      : I pledge my honor that I have abided by the Stevens Honor System.
#**********************************************************************************/
all:
	gcc -o chatclient chatclient.c util.h -Wall -Werror -pedantic-errors